Add 'Generate markdown documentation' command
GeoWerkstatt/vsc_interlis2_extension pull request #31
Opened 2024-10-09 09:27 UTC by domi-b

2024-10-09 11:24 UTC, danjov requested changes

2024-10-09 11:24 UTC, danjov commented on language-server/src/Geowerkstatt.Interlis.LanguageServer/FileContentCache.cs
> +public sealed class FileContentCache
REQ: Generell fehlt Code-Dokumentation aller Klassen und Methoden. Bitte überall ergänzen wo sinnvoll und `inheritdoc` verwenden, wo Interfaces implementiert werden.

2024-10-09 12:21 UTC, domi-b commented on .github/workflows/release.yml
> +      run: dotnet nuget add source --username "GeoWerkstatt-Build" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/GeoWerkstatt/ind
Ich habe das so aus der github Dokumentation übernommen: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry#authenticating-in-a-github-actions-workflow

Verschlüsselte Passwörter werden nur unter Windows unterstützt, aber ev. wäre es mit einer Umgebungsvariablen möglich: https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesourcecredentials

2024-10-09 13:58 UTC, domi-b commented on language-server/src/Geowerkstatt.Interlis.LanguageServer/Visitors/MarkdownDocumentationVisitor.cs
> +            var right = association.Content.LastOrDefault().Value;
Ich habe es jetzt klarer geschrieben mit `association.Content.Values.FirstOrDefault()`

2024-10-10 09:58 UTC, danjov approved these changes

2024-10-10 10:03 UTC, merged